# See http://www.appveyor.com/docs/appveyor-yml for many more options
image: Visual Studio 2019

version: 0.1.{build}

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

#clone_folder: c:\projects\PStSQLtTestGenerator
#clone_depth: 100
shallow_clone: true

environment:
  workingdirectory: c:\projects\
  workingfolder: c:\projects\PStSQLtTestGenerator
  environment: development
  version: 0.1.$(appveyor_build_number)
  appveyor_rdp_password: P$tSQLtTestG3nerator

services:
  - mssql2017

matrix:
  fast_finish: true

before_test:
- ps: .\build\appveyor-prerequisites.ps1

#build_script:
#- ps: .\build\appveyor-build.ps1

build: off

test_script:
# Test with PowerShell and Pester
- ps: .\build\appveyor-validate.ps1 -Finalize -IncludeCoverage

on_success:
- ps: .\build\appveyor-build.ps1 -AutoVersion

# Collecting results
#- ps: .\build\appveyor-validate.ps1 -Finalize -IncludeCoverage

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
