# See http://www.appveyor.com/docs/appveyor-yml for many more options
image: Visual Studio 2019

version: 0.3.{build}

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\Pester -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\PSFramework -> appveyor.yml
- C:\Program Files\WindowsPowerShell\Modules\dbatools -> appveyor.yml

shallow_clone: true

branches:
  only:
    - development

environment:
  workingfolder: c:\projects\PStSQLtTestGenerator
  environment: development
  version: 0.3.$(appveyor_build_number)
  appveyor_rdp_password: P$tSQLtTestG3nerator

matrix:
  fast_finish: true

before_build:
- ps: .\build\appveyor-prerequisites.ps1

test_script:
# Test with PowerShell and Pester
- ps: .\build\appveyor-validate.ps1 -IncludeCoverage

# Collecting results
- ps: .\build\appveyor-validate.ps1 -Finalize -IncludeCoverage

after_test:
- ps: .\build\appveyor-build.ps1

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
